### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jamesmacwilliam** [getkuby/kuby-core#116]
Love this concept, I missed the railsconf but I was lucky enough to see this on rubyweekly, I'm running into a bug when building.

## Description
- when running `KUBECONFIG=~/kubeconfig.yaml be kuby -e production build`
- I receive the error: `mapping values are not allowed in this context at line 18 column 45`

## Troubleshooting
- this seems to be coming from kubectl complaining about the yml file formatting

## Request
- is there a way for me to view the generated yml files that kube feeds to kubectl to debug this further?

**Comment by camertron** [comment]
Hey @jamesmacwilliam, thanks for asking about this. Let me address each point:

> when running `KUBECONFIG=~/kubeconfig.yaml be kuby -e production build`

While using an environment variable is a legit way to pass your kubeconfig to kubectl, it's not really the Kuby way™. I'm not sure which provider you're using, but if you want to specify your own kubeconfig I'd suggest adopting the [bare metal provider](https://getkuby.io/docs/customizing-deployments#the-bare-metal-provider) and using the `kubeconfig` configuration option to point it at your config.

> I receive the error: `mapping values are not allowed in this context at line 18 column 45`

This sounds like you have an error in your kubeconfig. The problem could reside in the YAML Kuby generates, but since Kuby uses a strict DSL and `YAML::dump` for generating resources, that seems fairly unlikely.

> is there a way for me to view the generated yml files that kuby feeds to kubectl to debug this further?

Although I'm pretty sure there's an issue with your kubeconfig, yes, Kuby can print out all the YAML it will send to the cluster:

```bash
be kuby -e production resources
```

**Comment by jamesmacwilliam** [comment]
this is perfect, the yml issue resolved when I tried it with a brand new app.  Thank you for this amazing resource, I don't think I would have approached kubernetes as an option vs a standard PAAS without it

**Comment by jamesmacwilliam** [comment]
is there something similar for the generated dockerfile image (ie: what would the default dockerfile look like)

**Comment by camertron** [comment]
Yes, you can run `be kuby -e production dockerfiles`. Happy kubing!
