### ISSUE TITLE
kuby-core (0.20.1) raise error on dotenv (3.0.1)

### ISSUE THREAD

**Issue by jessie19** [getkuby/kuby-core#137]
# Issue
When we run the
```shell
bundle exec kuby -h
```

We got this error
```ruby
error: undefined method `version' for Rails:Module

unless Gem::Requirement.new(">= 6.1").satisfied_by?(Gem::Version.new(Rails.version))
```

We noticed **dotenv (3.0.1)** make this [change](https://github.com/bkeepers/dotenv/blob/09caa4d08403770bf70bdd9f4b2404ea99e5312f/lib/dotenv/rails.rb#L1-L5) in this [PR](https://github.com/bkeepers/dotenv/pull/481).

It will be helpful if you have any insights about this error at **kuby-core (0.20.1)** side, thanks!

**Comment by camertron** [comment]
Hey @jessie19, this looks like a problem with your kuby config file. Kuby runs in the context of your bundle (via `bundle exec`), but doesn't `require` rails or load your app. That's why the `Rails` module doesn't respond to the `version` method.

I think you might be able to fix this problem by adding

```ruby
require "rails/version"
```

at the top of your kuby.rb config file. It needs to happen before dotenv loads, wherever that may be.

**Comment by jessie19** [comment]
> ```ruby
> rails/version
> ```

Hi @camertron,

Thanks for the info, we got this issue fix by adding below load before dotenv loads
```ruby
require 'rails'
require 'dotenv/load'
``` 

Thanks!
