### ISSUE TITLE
Database user and password for new setup

### ISSUE THREAD

**Issue by rept** [getkuby/kuby-core#33]
Hi,

I used to have my database.yml like this:

```
production:
  adapter:  postgresql
  host:     <%= ENV['DB_HOST'] %>
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool:     25
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  template: template0
```

Now I see in the kuby.rb file:

      add_plugin :rails_app do
        # configure database credentials
        database do
          user app_creds[:KUBY_DB_USER]
          password app_creds[:KUBY_DB_PASSWORD]
        end
      end

How does this work now?  Do I make up some username and password for the Postgres (since the container needs to be created anyway)?  Do I include that password in kuby.rb and in my database.yml or does kuby take care of the database.yml?

Or does kuby expose an environment variable that contains the DB_user, password, etc?

**Comment by camertron** [comment]
Hey @rept, thanks for asking about this. You should have the same username and password configured in both your database.yml and your kuby.rb config. In kuby.rb the credentials are used to create a database user so your app can connect when it starts. Kuby rewrites your database.yml, but only to inject the `host` field, i.e. it leaves the `username` and `password` fields alone.

I tried a bunch of different things when developing the database integration feature, and finally settled on this. It's simply too error-prone to do very much with database.yml because your Rails env isn't always available (by design). It's much easier to ask specifically for the database credentials in kuby.rb, although it does add a little more to the configuration.

**Comment by rept** [comment]
Ok clear!  Thanks.

**Comment by rept** [comment]
@camertron Does Kuby set an environment variable with the database password so this can be referenced?

For example, suppose I want my pass to be 'abc123'  I add this to app_creds, it would be great if I could set

    password: <%= ENV['DATABASE_PASSWORD'] %>

In my database.yml and have kuby fill in the environment variable when creating the pods.

**Comment by camertron** [comment]
Hey @rept, did you recently delete a comment on this issue? If so, did you get a satisfactory answer to your question?

**Comment by rept** [comment]
@camertron guilty!  It was a stupid question.  I wondered how I could avoid getting passwords into the database.yml file but I just need to reference the same encrypted key as I do from the kuby.rb

**Comment by camertron** [comment]
@rept gotcha, no problem!
