### ISSUE TITLE
Site not reachable: refused to connect.

### ISSUE THREAD

**Issue by rept** [getkuby/kuby-core#35]
I'm using Linode and deploy was succesful.  I can login to Rails console which works and has DB connection.  However I can't reach the site.

I'm getting:

This site can’t be reached 172.105.69.10 refused to connect.

Also the domain: https://bookingprovence.com isn't working.  Is there somewhere where we can follow what the TLS task is doing, if it's generating problems?

```
bundle exec kuby -e production remote status
NAME                             READY   STATUS    RESTARTS   AGE
cavadou-assets-c9764d48c-7lfrr   1/1     Running   0          35m
cavadou-web-5b87fbd567-lhj57     1/1     Running   0          35m
cavadou-web-postgres-0           1/1     Running   0          35m
cm-acme-http-solver-2sn99        1/1     Running   0          35m


bundle exec kuby -e production remote logs
[6] * Listening on http://0.0.0.0:8080
[6] Use Ctrl-C to stop
[6] - Worker 0 (pid: 7) booted, phase: 0
[6] - Worker 1 (pid: 8) booted, phase: 0
[6] - Worker 3 (pid: 10) booted, phase: 0
[6] - Worker 2 (pid: 9) booted, phase: 0
```

This is the kuby.rb

```
require 'active_support/core_ext'
require 'active_support/encrypted_configuration'

# Define a production Kuby deploy environment
Kuby.define('Cavadou') do
  environment(:production) do
    # Because the Rails environment isn't always loaded when
    # your Kuby config is loaded, provide access to Rails
    # credentials manually.
    app_creds = ActiveSupport::EncryptedConfiguration.new(
      config_path: File.join('config', 'credentials.yml.enc'),
      key_path: File.join('config', 'master.key'),
      env_key: 'RAILS_MASTER_KEY',
      raise_if_missing_key: true
    )

    docker do
      # Configure your Docker registry credentials here. Add them to your
      # Rails credentials file by running `bundle exec rake credentials:edit`.
      package_phase.remove(:yarn)
      delete :yarn_phase

      credentials do
        username app_creds.gitlab[:username]
        password app_creds.gitlab[:password]
        email app_creds.gitlab[:email]
      end

      # Configure the URL to your Docker image here, eg:
      # image_url 'foo.bar.com/me/myproject'
      #
      # If you're using Gitlab's Docker registry, try something like this:
      image_url 'registry.gitlab.com/rept/cavadou'
    end

    kubernetes do
      provider :linode do
        access_token app_creds.linode[:token]
        cluster_id app_creds.linode[:cluster]
      end

      # Add a plugin that facilitates deploying a Rails app.
      add_plugin :rails_app do
        hostname app_creds.domain_name
        # configure database credentials
        database do
          storage '1Gi'
          user 'rails_user'
          password app_creds.db[:password]
        end
      end

      provider :linode
    end
  end
end
```

**Comment by camertron** [comment]
@rept awesome, glad the deploy (finally) worked!

When it comes to making requests to your site, here are a couple of things to check:

1. Are you trying to hit the IP address of the node or the load balancer? Kuby should have defined an ingress object that corresponds to a load balancer visible in the Linode dashboard. Use that IP address instead of the one associated with the node.
2. Is your DNS set up correctly? Generally speaking, you'll need to point your domain's NS records to Linode's nameservers, then configure an A record in Linode to point to your load balancer's IP.
3. DNS records take some time to propagate around the world, usually between 24-48 hours. The cert-manager running in your cluster won't be able to generate a TLS certificate until DNS propagates thoroughly enough so that Let's Encrypt can make a successful request to your site.
4. You can make requests with cURL to see if things are working. You'll need to pass a few special flags. Here's an example assuming 172.105.69.10 is the IP address to your load balancer:

    ```
    curl -vvv -H 'Host: bookingprovence.com' --insecure https://172.105.69.10
    ```
    `-v` means verbose, `-H` adds a header, and `--insecure` skips TLS verification (since your cert may not have been issued yet).

Hope that helps!

**Comment by rept** [comment]
> 1. Are you trying to hit the IP address of the node or the load balancer? Kuby should have defined an ingress object that corresponds to a load balancer visible in the Linode dashboard. Use that IP address instead of the one associated with the node.

This was it!  I had filled in the IP address of the cluster instead of the load balancer.  After this it worked!  Thanks!!!

BTW I didn't need to change NS records to Linode.

**Comment by camertron** [comment]
Sweet, glad to hear you got it working!
