### ISSUE TITLE
Pods can't spread across nodes with ReadWriteOnce volumes

### ISSUE THREAD

**Issue by lazyatom** [getkuby/kuby-core#42]
I'm seeing this on Linode but I suspect it's general; when I increase the number of nodes in my pool from one to two, and increase the replicas for the rails app in `kuby.rb`, then pods that are started on the new node fail to start because they cannot mount the block storage ("volume" in Linode parlance). I believe this is because Linode (and other providers, from what I can tell) limit volume connection to a single node.

I _believe_ the volume is only being used for serving assets, once the deployment is actually running, so in theory, after deployment, only the assets pod(s) need to be connected to that volume, and they could be connected read-only. I'm not sure how to handle during deployments though. And generally my understanding might have huge holes or mistakes.

But the gist of it is, while we're mounting the assets volume as `ReadWriteOnce`, I don't think we can scale assets or web pods across multiple nodes.

**Comment by camertron** [comment]
@lazyatom shoot you're absolutely right. I didn't think about the multi-node issue when developing the asset server feature. The asset server serves the assets from the volume, and new assets are copied over on each deploy by mounting the same volume to one of the init containers ("copy-assets"). I've never run into this personally because I've always only spun up single-node clusters.

I'm thinking Kuby should only ever mount the volume onto the asset server and use rsync or ssh or something to copy assets over. Some providers support mounting volumes read-only across nodes, but I'm pretty sure others don't. For example, this is what the Linode documentation says:

> Currently the only mode supported by the Linode Block Storage CSI driver is `ReadWriteOnce`, meaning that it can only be connected to one Kubernetes node at a time.

**Comment by lazyatom** [comment]
I've been thinking about approaches we could take for this. One of my main motivations for exploring k8s is the resilience of nodes, since I'm sick of my apps having downtime while my host reboots hardware, so I'm very motivated!

I haven't been able to find a k8s-native way of moving files between nodes _without_ using shared volumes, nor can I figure out a simple way of having the `app` containers mount a volume, write to it, and then unmount it. And either way, if the asset pods are spread across nodes, then each node will require its own volume just to hold the same copy of the assets, since as far as I can tell, it's just not possible to generally mount the volumes on more than one node (as you say above, it's certainly the case for Linode).

 Here are a few options we could consider:

1. somehow arrange that each node has one or more associated volume stores, and that each pod only tries to mount volume(s) from the node it is running on.
1. build a secondary `assets` image based on the nginx one, and copy the built assets from the `app` image into the asset one as part of `kuby build`. Then push and deploy both images. No shared volume required, so easily scaleable, but during deployment, newer `app` pods may link to assets that older `assets` pods don't contain.
2. on deployment, copy assets from the `app` container into the providers _object_ storage (e.g. S3 or equivalent), and set up the `assets` pod to mount or download the assets from there when it starts. Again, no shared volume used. Since object storage can contain assets for multiple deployments, old and new `app` pods can be supported by any `assets` pod.
3. similar to above, but configure the assets to be served directly from the provider object storage, removing the need for the `assets` pod entirely; this is spreading the deployment a little outside of Kubernetes, but again, very scaleable
4. include [Minio](http://min.io) pod(s), backed by shared volume(s), and upload assets into _that_, and have it act as a backend for `assets` pods. This is provider-independent, but more complicated.
4. configure the `app` container to serve assets as well as the app (via `RAILS_SERVE_STATIC_ASSETS`), and then configure nginx on the the `assets` pods to have _all_ the `app` pods (regardless of node, potentially regardless of deployment) as backends, and then act as a proxy/cache for asset requests.
5. have the `app` containers package up a tar.gz of built assets and make them available at a known URL (or one that can be signalled to the other pods somehow), which they can then download and unpack when they start.
6. create a new image based on the nginx one, and run an rsync daemon in it, and then (somehow!) on deployment discover all `assets` pods (old and new) and trigger the sync between them all, and all `app` pods (old and new), such that all `assets` pods end up with merged mirrors of the build assets from all `app` pods.

I think the *right* approach might be on of the object storage ones, either using native provider object stores or bundling Minio with a volume store. In the latter case, there's still a resilience question since you'd need multiple Minio pods spread across multiple nodes, each with their own volume, in order to avoid downtime, but that problem can (probably) be delegated to Minio's replication features.

Anyway, hopefully some of that is useful, even if only to rule some of the approaches out.

**Comment by camertron** [comment]
Hey @lazyatom, thanks for this superb writeup, there's a lot of great stuff here.

1. This is interesting, but would be difficult to implement and enforce, especially considering that we don't necessarily have control over which node k8s will schedule a pod to run on. I should rephrase that: we _do_ have control over which node a pod runs on via affinity and anti-affinity rules, but IMHO using them for something like this goes against the k8s abstractions in a pretty big way. We shouldn't need to care _where_ our pods run, only that they're running _somewhere_ on the cluster's available resources.
1. I like this idea. We'd have to make some changes to Kuby's internals to have it build and push more than one Docker image, and somehow tie those two images to each other so they both get deployed at the same time. We could continue using a shared volume to keep old assets from the previous deploy around for a while (this is what the current asset copying code does, i.e. keeps around assets from previous deploys and does some intelligent symlinking).
1. Making use of a 3rd-party object storage system like S3 is how I've seen assets for Rails apps handled at previous jobs. In such setups, a CDN fetches new assets directly from the object store and caches them for future requests. Browsers talk to the CDN and bypass the Rails app. As you've identified in number 5, we could even stand up Minio or similar inside the cluster so no 3rd-party services are necessary. I'm hesitant to go the 3rd-party service route because I think that one of Kuby's big pros is that it doesn't require any external services (which almost surely cost extra money). At the same time, I'm hesitant to add something like Minio into the mix because of the added complexity and resources it will take up in the cluster. Kuby already pushes the memory and CPU limitations of a single $15/mo Linode or DigitalOcean node as it is.
1. See number 3 above.
1. See number 3 above.
1. This is probably the simplest and most straightforward approach. It's very similar to the CDN technique I mentioned in number 3. Unfortunately it suffers from the stale asset problem since the asset server may hit a new or old Rails pod which may or may not have the requested asset.
1. Yeah, I've thought a lot about this sort of idea in general, i.e. somehow setting up communication between pods to enable copying assets via SSH, rsync, or this .tar.gz scheme. Unfortunately opening up SSH ports could be insecure, but even more at issue is the timing. The Rails pod needs to be up and running so the .tar.gz file can be requested, but by then it will also be serving requests. By the time the asset pod has requested, unpacked, and moved the assets into the right location, a number of requests may have been served.
1. Interesting, but sadly requires SSH/rsync access between pods.

I do think you're correct in saying the _right_ approach is likely to use an object storage system, and by "right" I mean technically correct. In the back of my mind I keep thinking, "Surely it has to be easier than that? We're just talking about copying some files!" So here's another potential solution: keep the asset server with the attached volume we have now. On each deploy, extract the assets from the Docker image we're about to deploy, and use [`kubectl cp`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp) to copy and symlink the assets. What do you think?

**Comment by lazyatom** [comment]
Thanks for the detailed response -- however we proceed, I complete agree that we should avoid working _against_ k8s abstractions. I also totally agree about avoiding creating any sort of custom images with rsync/ssh on them -- the beauty of the current asset pods is that they use a standard community-tested image 👍

With approach 2 (copy the files into an `assets` image during `kuby build`), I guess we'd have to built the `assets` image with the new assets in some ancillary directory within the image, and then have it copy (merge) those files onto the shared volume ones the pod starts? I think that could work, with the shared volume caveat below.

Extracting the assets from the `app` image on deploy sounds very reasonable too, though `kubectl cp` looks to be [going away](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/20190920-future-of-kubectl-cp.md), but I'm sure there will be other ways to extract files from pods. So to check I understand, we'd use `kubectl cp` running on the deploying computer to copy files extracted from the local `app` image, and then sending those files to one/all of the `assets` containers running in the cluster?

With all the approaches that continue to involve a shared volume (including the two we've focussed on above), I think we unavoidably have to figure out some way to prevent pods, even if it's only the `assets` pods, from trying to attach volumes that are already attached to different nodes. This feels both fundamentally unavoidable, and fundamentally bizarre that we should have to worry about it at all, but perhaps it's a limitation of the various k8s deployments (e.g. LKE).

So with that in mind, one final pitch for the object store approach is that it would be the responsibility of each _provider gem_ (kuby-linode, kuby-eks, etc) to provide this functionality in a provider-native way, since I _think_ that each provide does have an equivalent _1st-party_ service:

* EKS -- S3
* Azure -- Blob Storage
* Linode -- Object Storage
* DigitalOcean -- Spaces

I think S3 and Linode Object Storage can act as backends for nginx, by being configured to serve HTTP (e.g. the pipeline to assets would be Ingress -> nginx on `assets` pod -> HTTP access to object storage); I know less about the Azure/DigitalOcean offerings but at a pinch the deployment could just copy a complete bucket into the new `assets` container(s) and nginx could serve those files as it currently does. In fact, if that's the lowest common denominator then maybe all the providers could work that way. I suspect that S3 and Linode Object Storage are also cheaper than volume storage; Linode's smallest volume is 10GB, and I'm never going to fill that with assets! 😅 I think object storage is an approach that could be explored in parallel with the either of the two above too.

**Comment by camertron** [comment]
Hey @lazyatom, finally circling back on this.

Interesting, I didn't know `kubectl cp` is regarded as a security issue and may be going away - I'd say that's a good reason to avoid using it :(

Initially I thought we could do away with the shared volume entirely and create individual asset PVs per pod/replica. Unfortunately after doing some additional research, I've come to understand that it's not currently possible to tell k8s deployments you want a separate PV per-pod. You can do it with this thing called a "stateful set" via the `volumeClaimTemplates` section, but the same is not available in deployments. For that reason I think it might be best to do away with shared volumes altogether - they just aren't flexible enough at present.

I suppose the most promising solutions are still 1) a separate assets Docker image, and 2) provider-based object storage. What do you envision the interface being for the object storage solution, i.e. what methods would be available on the derived `Provider` classes? Maybe `store_file` and `retrieve_file`? I'm still hesitant to go the object storage route for the following reasons:

1. It's complicated to implement and requires all providers to make changes.
1. It potentially comes with additional costs to the developer.
1. It requires additional setup steps. You have to explicitly flip a switch in Linode's interface, for example. You also have to generate a separate keypair and store the access/secret keys somewhere.

It's interesting to note that most of the providers (perhaps all?) feature an S3-compatible API. It seems S3 is the gold standard. In fact, I was able to use the AWS SDK ruby gem to store and retrieve files from a bucket in Linode's object storage system pretty easily. A bit of Googling reveals DigitalOcean's Spaces object storage is also S3-compatible.

In my opinion the remaining solution, i.e. a separate Docker image, gives us what we want at a marginal cost. The image can be built during the normal `kuby build` step. If we sprinkle in a bit of cleverness, we could achieve the same guarantees of the shared PV approach, namely keeping around 2 or more asset versions to avoid the stale assets issue. Here's how I envision the build process:

1. Build the original Rails Docker image, which includes asset compilation (i.e. the same thing we're already doing)
1. Mount the Rails Docker image _and_ the previous (i.e. latest) assets image using `FROM ... AS` Docker directives.
1. Copy over the assets directory from the previous assets image.
1. Run the `kuby:rails_app:assets:copy` task to copy and symlink in all the new assets. This should be possible because the Rails Docker image contains everything we need to run Kuby tasks.
1. Add a third `FROM nginx` directive. The last `FROM` directive takes precedence, meaning nginx will become the final base image, leaving behind all the Ruby/Rails baggage.
1. Copy merged assets.
1. Push image to registry.

There are a number of nice properties of this approach:

1. No PVs at all!
1. Possible without extra configuration or steps the developer has to perform.
1. You get versioned asset images that can be run anywhere without additional provider support (like object or block storage).
1. Complicated, but within the realm of sanity, I would say.

Curious what you think!

**Comment by camertron** [comment]
Fixed as of v0.12.0 🎉
